#! /usr/bin/env ruby
# because rubygems shims assume a gem's executables are Ruby

require "shellwords"
require "sprockets-esbuild/upstream"

supported_platforms = SprocketsEsbuild::Upstream::NATIVE_PLATFORMS.keys

if supported_platforms.none? { |supported_platform| Gem::Platform.match(supported_platform) }
  STDERR.puts(<<~ERRMSG)
    ERROR: sprockets-esbuild does not support the #{::Gem::Platform.local} platform
  ERRMSG
  exit 1
end

exe_path = Dir.glob(File.join(__dir__, "*", "esbuild")).find do |f|
  Gem::Platform.match(File.basename(File.dirname(f)))
end
if exe_path.nil?
  STDERR.puts(<<~ERRMSG)
    ERROR: Cannot find the esbuild executable for #{::Gem::Platform.local} in #{__dir__}
    If you're using bundler, please make sure you're on the latest bundler version:

      gem install bundler
      bundle update --bundler

    Then make sure your lock file includes this platform by running:

      bundle lock --add-platform #{::Gem::Platform.local}
      bundle install

    See `bundle lock --help` output for details.
  ERRMSG
  exit 1
end

command = Shellwords.join([exe_path, ARGV].flatten)
exec(command)
