name: Native Gems
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize]
    branches:
      - '*'

jobs:
  package:
    strategy:
      fail-fast: false
      matrix:
        platform: ["ruby", "x64-mingw32", "x86_64-darwin", "x86_64-linux"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.0"
          bundler: latest
          bundler-cache: true
      - run: "rake gem:${{matrix.platform}}"
      - uses: actions/upload-artifact@v2
        with:
          name: gem-${{matrix.platform}}
          path: pkg
          retention-days: 1

  vanilla-install:
    needs: ["package"]
    runs-on: ubuntu-latest
    steps:
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.0"
      - uses: actions/download-artifact@v2
        with:
          name: gem-ruby
          path: pkg
      - run: "gem install pkg/sprockets-esbuild-*.gem"
      - run: "esbuild 2>&1 | fgrep 'ERROR: Cannot find the esbuild executable'"

  linux-install:
    needs: ["package"]
    runs-on: ubuntu-latest
    steps:
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.0"
      - uses: actions/download-artifact@v2
        with:
          name: gem-x86_64-linux
          path: pkg
      - run: "gem install pkg/sprockets-esbuild-*.gem"
      - run: "esbuild --help"

  darwin-install:
    needs: ["package"]
    runs-on: macos-latest
    steps:
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.0"
      - uses: actions/download-artifact@v2
        with:
          name: gem-x86_64-darwin
          path: pkg
      - run: "gem install pkg/sprockets-esbuild-*.gem"
      - run: "esbuild --help"

  windows-install:
    needs: ["package"]
    runs-on: windows-latest
    steps:
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.0"
      - uses: actions/download-artifact@v2
        with:
          name: gem-x64-mingw32
          path: pkg
      - run: "gem install pkg/sprockets-esbuild-*.gem"
      - run: "esbuild --help"
